kind: Service
apiVersion: v1
metadata:
  name: mini-kafka-ssl
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
    name: kafka
  type: NodePort