kafka:
  replicas: 1
  configurationOverrides:
    num.partitions: 1
    offsets.topic.replication.factor: 1
    log.retention.hours: -1
    log.retention.bytes: -1
    default.replication.factor: 1
    min.insync.replicas: 1
    listeners: PLAINTEXT://:9092,EXTERNAL://localhost:9093,SSL://:9091
    advertised.listeners: EXTERNAL://localhost:9093,SSL://:9091
    listener.security.protocol.map: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL
    inter.broker.listener.name: SSL
    ssl.client.auth: required
    ssl.enabled.protocols: TLSv1.2
    ssl.keystore.filename: kafka.keystore.jks
    ssl.truststore.filename: kafka.truststore.jks
    ssl.key.credentials: pw.txt
    ssl.keystore.credentials: pw.txt
    ssl.truststore.credentials: pw.txt
  kafkaHeapOptions: "-Xmx512M -Xms512M"
  secrets:
  - name: kafka-jks
    keys:
      - kafka.keystore.jks
      - kafka.truststore.jks
      - pw.txt
    mountPath: /etc/kafka/secrets
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 1Gi
      cpu: 500m
  zookeeper:
    replicaCount: 1
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 500Mi
        cpu: 500m
    env: {ZK_HEAP_SIZE: "512M"}